import {
  TOP3_THEMES,
  Top3ThemeSuggestionSource,
} from '@/constants/top3-themes';
import { CollectionOption } from '@/types/collection-option';

function getThemeProviderFields(
  suggestionSource?: Top3ThemeSuggestionSource
): Pick<
  CollectionOption,
  'providerKey' | 'providerMode' | 'providerConfig'
> {
  if (!suggestionSource) {
    return {
      providerMode: 'curated',
      providerConfig: {},
    };
  }

  return {
    providerKey: 'tmdb',
    providerMode: 'discover',
    providerConfig: {
      ...(suggestionSource.primaryReleaseDateGte
        ? {
            primaryReleaseDateGte:
              suggestionSource.primaryReleaseDateGte,
          }
        : {}),
      ...(suggestionSource.primaryReleaseDateLte
        ? {
            primaryReleaseDateLte:
              suggestionSource.primaryReleaseDateLte,
          }
        : {}),
      ...(suggestionSource.withPeople !== undefined
        ? {
            withPeople:
              suggestionSource.withPeople,
          }
        : {}),
      ...(suggestionSource.withCompanies !== undefined
        ? {
            withCompanies:
              suggestionSource.withCompanies,
          }
        : {}),
    },
  };
}

const MOVIE_TYPE_FALLBACKS: CollectionOption[] = [
  {
    id: 'movies-type-actors',
    slug: 'actors',
    categoryId: 'movies',
    kind: 'type',
    name: 'Actors',
    groupName: 'people',
    keywords: [],
    searchHints: [],
    featured: false,
    trendingEnabled: false,
    active: true,
    displayOrder: 10,
    entityKind: 'person',
    providerKey: 'tmdb',
    providerMode: 'movie_person',
    providerConfig: {
      personType: 'actors',
    },
  },
  {
    id: 'movies-type-directors',
    slug: 'directors',
    categoryId: 'movies',
    kind: 'type',
    name: 'Directors',
    groupName: 'people',
    keywords: [],
    searchHints: [],
    featured: false,
    trendingEnabled: false,
    active: true,
    displayOrder: 20,
    entityKind: 'person',
    providerKey: 'tmdb',
    providerMode: 'movie_person',
    providerConfig: {
      personType: 'directors',
    },
  },
];

const MOVIE_THEME_FALLBACKS: CollectionOption[] =
  TOP3_THEMES.map((theme, index) => ({
    id: `movies-theme-${theme.id}`,
    slug: theme.id,
    categoryId: theme.category,
    kind: 'theme',
    name: theme.name,
    groupName: theme.group,
    browseLabel: theme.browseLabel,
    keywords: theme.keywords,
    searchHints: theme.searchHints ?? [],
    featured: theme.featured ?? false,
    trendingEnabled:
      theme.trendingEnabled ?? false,
    active: true,
    displayOrder: (index + 1) * 10,
    entityKind: 'movie',
    ...getThemeProviderFields(
      theme.suggestionSource
    ),
  }));

const ARTIST_THEME_FALLBACKS: CollectionOption[] = [
  {
    id: 'artists-theme-1960s-artists',
    slug: '1960s-artists',
    categoryId: 'artists',
    kind: 'theme',
    name: '1960s Artists',
    groupName: 'era',
    browseLabel:
      'The artists who defined the sound and culture of the decade',
    keywords: ['1960s', '1960', '60s', 'sixties'],
    searchHints: ['Defining artists of the 1960s', '60s music icons'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 10,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-1970s-artists',
    slug: '1970s-artists',
    categoryId: 'artists',
    kind: 'theme',
    name: '1970s Artists',
    groupName: 'era',
    browseLabel:
      'The artists who defined the sound and culture of the decade',
    keywords: ['1970s', '1970', '70s', 'seventies'],
    searchHints: ['Defining artists of the 1970s', '70s music icons'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 20,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-1980s-artists',
    slug: '1980s-artists',
    categoryId: 'artists',
    kind: 'theme',
    name: '1980s Artists',
    groupName: 'era',
    browseLabel:
      'The artists who defined the sound and culture of the decade',
    keywords: ['1980s', '1980', '80s', 'eighties'],
    searchHints: ['Defining artists of the 1980s', '80s music icons'],
    featured: true,
    trendingEnabled: true,
    active: true,
    displayOrder: 30,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-1990s-artists',
    slug: '1990s-artists',
    categoryId: 'artists',
    kind: 'theme',
    name: '1990s Artists',
    groupName: 'era',
    browseLabel:
      'The artists who defined the sound and culture of the decade',
    keywords: ['1990s', '1990', '90s', 'nineties'],
    searchHints: ['Defining artists of the 1990s', '90s music icons'],
    featured: true,
    trendingEnabled: true,
    active: true,
    displayOrder: 40,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-2000s-artists',
    slug: '2000s-artists',
    categoryId: 'artists',
    kind: 'theme',
    name: '2000s Artists',
    groupName: 'era',
    browseLabel:
      'The artists who defined the sound and culture of the decade',
    keywords: ['2000s', '2000', '00s', 'aughts'],
    searchHints: ['Defining artists of the 2000s', '2000s music icons'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 50,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-2010s-artists',
    slug: '2010s-artists',
    categoryId: 'artists',
    kind: 'theme',
    name: '2010s Artists',
    groupName: 'era',
    browseLabel:
      'The artists who defined the sound and culture of the decade',
    keywords: ['2010s', '2010', '10s'],
    searchHints: ['Defining artists of the 2010s', '2010s music icons'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 60,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-2020s-artists',
    slug: '2020s-artists',
    categoryId: 'artists',
    kind: 'theme',
    name: '2020s Artists',
    groupName: 'era',
    browseLabel:
      'The artists defining the sound and culture of the decade',
    keywords: ['2020s', '2020', '20s', 'current'],
    searchHints: ['Artists defining the 2020s', 'Current music icons'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 70,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-road-trip',
    slug: 'road-trip',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Road Trip Artists',
    groupName: 'mood',
    browseLabel:
      'The artists you want on the soundtrack to a long drive',
    keywords: ['road trip', 'driving', 'drive', 'travel'],
    searchHints: ['Artists for a road trip', 'Driving music'],
    featured: true,
    trendingEnabled: true,
    active: true,
    displayOrder: 80,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-late-night',
    slug: 'late-night',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Late-Night Artists',
    groupName: 'mood',
    browseLabel:
      'The artists that sound best after dark',
    keywords: ['late night', 'night', 'after dark', 'evening'],
    searchHints: ['Late-night listening', 'Artists for after dark'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 90,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-party',
    slug: 'party',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Party Artists',
    groupName: 'mood',
    browseLabel:
      'The artists guaranteed to get the room moving',
    keywords: ['party', 'dance', 'celebration', 'energy'],
    searchHints: ['Artists for a party', 'Party favourites'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 100,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-rainy-day',
    slug: 'rainy-day',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Rainy Day Artists',
    groupName: 'mood',
    browseLabel:
      'The artists that fit a quiet, grey day',
    keywords: ['rainy day', 'rain', 'quiet', 'moody'],
    searchHints: ['Artists for a rainy day', 'Moody listening'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 110,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-listening-right-now',
    slug: 'listening-right-now',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Listening Right Now',
    groupName: 'personal',
    browseLabel:
      'The artists currently dominating your rotation',
    keywords: ['current', 'right now', 'rotation', 'recent', 'listening'],
    searchHints: ['Artists on repeat right now', 'Current favourites'],
    featured: true,
    trendingEnabled: true,
    active: true,
    displayOrder: 120,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-discovered-late',
    slug: 'discovered-late',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Discovered Late',
    groupName: 'personal',
    browseLabel:
      'Artists you somehow missed the first time around',
    keywords: ['discovered', 'late', 'recent discovery', 'missed'],
    searchHints: ['Artists I found years later', 'Late discoveries'],
    featured: true,
    trendingEnabled: true,
    active: true,
    displayOrder: 130,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-came-around-on',
    slug: 'came-around-on',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Came Around On',
    groupName: 'personal',
    browseLabel:
      'Artists you didn’t connect with at first, but do now',
    keywords: ['changed my mind', 'grew on me', 'came around', 'appreciate now'],
    searchHints: ['Artists who grew on me', 'Artists I changed my mind about'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 140,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-wish-id-seen-live',
    slug: 'wish-id-seen-live',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Wish I’d Seen Live',
    groupName: 'live',
    browseLabel:
      'Artists you wish you could have experienced in their prime',
    keywords: ['live', 'concert', 'prime', 'peak', 'wish I saw'],
    searchHints: ['Legendary live acts', 'Artists I wish I had seen'],
    featured: true,
    trendingEnabled: true,
    active: true,
    displayOrder: 150,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-worth-travelling-for',
    slug: 'worth-travelling-for',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Worth Travelling For',
    groupName: 'live',
    browseLabel:
      'Artists you’d plan a trip around to see live',
    keywords: ['live', 'concert', 'travel', 'tour', 'road trip'],
    searchHints: ['Artists worth travelling for', 'Must-see live acts'],
    featured: true,
    trendingEnabled: true,
    active: true,
    displayOrder: 160,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-best-debut-albums',
    slug: 'best-debut-albums',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Best Debut Albums',
    groupName: 'career',
    browseLabel:
      'Artists who made an exceptional first impression',
    keywords: ['debut', 'debut album', 'first album', 'first record'],
    searchHints: ['Best debut albums', 'Great first records'],
    featured: true,
    trendingEnabled: true,
    active: true,
    displayOrder: 170,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-best-reinventions',
    slug: 'best-reinventions',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Best Reinventions',
    groupName: 'career',
    browseLabel:
      'Artists who successfully evolved their sound or identity',
    keywords: ['reinvention', 'reinvented', 'evolution', 'changed sound', 'changed style'],
    searchHints: ['Best artist reinventions', 'Artists who evolved'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 180,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
  {
    id: 'artists-theme-deserve-a-comeback',
    slug: 'deserve-a-comeback',
    categoryId: 'artists',
    kind: 'theme',
    name: 'Deserve a Comeback',
    groupName: 'career',
    browseLabel:
      'Artists you’d love to see return with something new',
    keywords: ['comeback', 'return', 'reunion', 'new music', 'revival'],
    searchHints: ['Artists who should come back', 'Acts ready for a return'],
    featured: false,
    trendingEnabled: true,
    active: true,
    displayOrder: 190,
    entityKind: 'artist',
    providerMode: 'curated',
    providerConfig: {},
  },
];

export const BUNDLED_COLLECTION_OPTIONS: CollectionOption[] = [
  ...MOVIE_TYPE_FALLBACKS,
  ...MOVIE_THEME_FALLBACKS,
  ...ARTIST_THEME_FALLBACKS,
];
