export type Top3Item = {
  id: string;
  title: string;
  subtitle?: string;
  releaseYear?: string;
  genres?: string[];
  imageUrl?: string;
  rating?: number;
  previewUrl?: string;
  previewSongId?: string;
  previewSongTitle?: string;
  previewRecordingArtist?: string;
  previewRecordingGenre?: string;
  appleMusicUrl?: string;
  appleMusicArtistId?: string;
  albumName?: string;
  applePodcastId?: string;
  applePodcastsUrl?: string;
  podcastFeedUrl?: string;
  podcastDescription?: string;
  trailerVideoId?: string;
  googleBooksVolumeId?: string;
};
