create table public.musicians (
  id text primary key,
  name text not null,
  normalized_name text not null,
  sort_name text not null,
  musicbrainz_id text,
  wikidata_id text,
  apple_music_artist_id text,
  image_status text not null default 'pending',
  active boolean not null default true,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint musicians_id_check
    check (btrim(id) <> ''),

  constraint musicians_name_check
    check (btrim(name) <> ''),

  constraint musicians_normalized_name_check
    check (btrim(normalized_name) <> ''),

  constraint musicians_sort_name_check
    check (btrim(sort_name) <> '')
);

alter table public.musicians
  enable row level security;

create index musicians_search_idx
  on public.musicians (
    active,
    normalized_name
  );

create index musicians_sort_idx
  on public.musicians (
    active,
    sort_name
  );

create unique index musicians_musicbrainz_id_key
  on public.musicians (musicbrainz_id)
  where musicbrainz_id is not null;

create unique index musicians_wikidata_id_key
  on public.musicians (wikidata_id)
  where wikidata_id is not null;

create unique index musicians_apple_music_artist_id_key
  on public.musicians (apple_music_artist_id)
  where apple_music_artist_id is not null;


create table public.musician_roles (
  musician_id text not null
    references public.musicians(id)
    on delete cascade,
  role text not null,
  rank integer not null,
  confidence text not null,
  source text,
  source_reference text,
  approved boolean not null default true,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  primary key (
    musician_id,
    role
  ),

  constraint musician_roles_role_check
    check (
      role in (
        'vocalist',
        'guitarist',
        'drummer',
        'bassist',
        'mc',
        'dj'
      )
    ),

  constraint musician_roles_rank_check
    check (rank > 0),

  constraint musician_roles_confidence_check
    check (btrim(confidence) <> ''),

  constraint musician_roles_role_rank_key
    unique (
      role,
      rank
    )
);

alter table public.musician_roles
  enable row level security;

create index musician_roles_browse_idx
  on public.musician_roles (
    role,
    approved,
    rank
  );


create table public.musician_aliases (
  id bigint generated by default as identity primary key,
  musician_id text not null
    references public.musicians(id)
    on delete cascade,
  alias text not null,
  normalized_alias text not null,
  alias_type text not null,
  active boolean not null default true,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint musician_aliases_alias_check
    check (btrim(alias) <> ''),

  constraint musician_aliases_normalized_alias_check
    check (btrim(normalized_alias) <> ''),

  constraint musician_aliases_alias_type_check
    check (btrim(alias_type) <> ''),

  constraint musician_aliases_musician_alias_key
    unique (
      musician_id,
      normalized_alias
    )
);

alter table public.musician_aliases
  enable row level security;

create index musician_aliases_search_idx
  on public.musician_aliases (
    active,
    normalized_alias
  );

create index musician_aliases_musician_idx
  on public.musician_aliases (
    musician_id,
    active
  );


create policy "Active musicians are readable"
  on public.musicians
  for select
  to public
  using (active);

create policy "Approved musician roles are readable"
  on public.musician_roles
  for select
  to public
  using (
    approved
    and exists (
      select 1
      from public.musicians musician
      where
        musician.id = musician_id
        and musician.active
    )
  );

create policy "Active musician aliases are readable"
  on public.musician_aliases
  for select
  to public
  using (
    active
    and exists (
      select 1
      from public.musicians musician
      where
        musician.id = musician_id
        and musician.active
    )
  );


grant select
  on table public.musicians
  to anon, authenticated;

grant select
  on table public.musician_roles
  to anon, authenticated;

grant select
  on table public.musician_aliases
  to anon, authenticated;

grant all
  on table public.musicians
  to postgres, service_role;

grant all
  on table public.musician_roles
  to postgres, service_role;

grant all
  on table public.musician_aliases
  to postgres, service_role;

grant all
  on sequence public.musician_aliases_id_seq
  to postgres, service_role;


create or replace function public.set_musician_catalogue_updated_at()
returns trigger
language plpgsql
set search_path to ''
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create trigger set_musicians_updated_at
  before update on public.musicians
  for each row
  execute function public.set_musician_catalogue_updated_at();

create trigger set_musician_roles_updated_at
  before update on public.musician_roles
  for each row
  execute function public.set_musician_catalogue_updated_at();

create trigger set_musician_aliases_updated_at
  before update on public.musician_aliases
  for each row
  execute function public.set_musician_catalogue_updated_at();


insert into public.collection_options (
  id,
  slug,
  category_id,
  kind,
  name,
  group_name,
  browse_label,
  keywords,
  search_hints,
  featured,
  trending_enabled,
  active,
  display_order,
  entity_kind,
  provider_key,
  provider_mode,
  provider_config
)
values
  (
    'artists-type-vocalists',
    'vocalists',
    'artists',
    'type',
    'Vocalists',
    'roles',
    null,
    array[
      'singer',
      'singers',
      'vocalist',
      'vocalists'
    ],
    array[
      'Favourite vocalists',
      'Greatest singers'
    ],
    false,
    false,
    true,
    10,
    'artist',
    'top3_catalogue',
    'musician_role',
    '{"role":"vocalist"}'::jsonb
  ),
  (
    'artists-type-guitarists',
    'guitarists',
    'artists',
    'type',
    'Guitarists',
    'roles',
    null,
    array[
      'guitar',
      'guitarist',
      'guitarists',
      'guitar player'
    ],
    array[
      'Favourite guitarists',
      'Greatest guitar players'
    ],
    false,
    false,
    true,
    20,
    'artist',
    'top3_catalogue',
    'musician_role',
    '{"role":"guitarist"}'::jsonb
  ),
  (
    'artists-type-drummers',
    'drummers',
    'artists',
    'type',
    'Drummers',
    'roles',
    null,
    array[
      'drums',
      'drummer',
      'drummers'
    ],
    array[
      'Favourite drummers',
      'Greatest drummers'
    ],
    false,
    false,
    true,
    30,
    'artist',
    'top3_catalogue',
    'musician_role',
    '{"role":"drummer"}'::jsonb
  ),
  (
    'artists-type-bassists',
    'bassists',
    'artists',
    'type',
    'Bassists',
    'roles',
    null,
    array[
      'bass',
      'bassist',
      'bassists',
      'bass player'
    ],
    array[
      'Favourite bassists',
      'Greatest bass players'
    ],
    false,
    false,
    true,
    40,
    'artist',
    'top3_catalogue',
    'musician_role',
    '{"role":"bassist"}'::jsonb
  ),
  (
    'artists-type-mcs',
    'mcs',
    'artists',
    'type',
    'MCs',
    'roles',
    null,
    array[
      'mc',
      'mcs',
      'rapper',
      'rappers',
      'rap'
    ],
    array[
      'Favourite MCs',
      'Greatest rappers'
    ],
    false,
    false,
    true,
    50,
    'artist',
    'top3_catalogue',
    'musician_role',
    '{"role":"mc"}'::jsonb
  ),
  (
    'artists-type-djs',
    'djs',
    'artists',
    'type',
    'DJs',
    'roles',
    null,
    array[
      'dj',
      'djs',
      'disc jockey',
      'turntablist'
    ],
    array[
      'Favourite DJs',
      'Greatest DJs'
    ],
    false,
    false,
    true,
    60,
    'artist',
    'top3_catalogue',
    'musician_role',
    '{"role":"dj"}'::jsonb
  );
