SET local check_function_bodies = off;

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "service_role";

CREATE EXTENSION "pg_net" SCHEMA "extensions";

CREATE TABLE "public"."apple_auth_tokens" (
  "user_id"       uuid                     NOT NULL,
  "refresh_token" text                     NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "apple_auth_tokens_pkey" PRIMARY KEY (user_id)
);

ALTER TABLE "public"."apple_auth_tokens"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."blocks" (
  "blocker_id"      uuid                     NOT NULL,
  "blocked_user_id" uuid                     NOT NULL,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "blocks_cannot_block_self" CHECK ((blocker_id <> blocked_user_id)),
  CONSTRAINT "blocks_pkey" PRIMARY KEY (blocker_id, blocked_user_id)
);

ALTER TABLE "public"."blocks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."collections" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"      uuid                     NOT NULL,
  "category"     text                     NOT NULL,
  "topic"        text,
  "title"        text                     NOT NULL,
  "status"       text                     NOT NULL DEFAULT 'draft'::text,
  "items"        jsonb                    NOT NULL DEFAULT '[]'::jsonb,
  "published_at" timestamp with time zone,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "type"         text,
  "removed_at"   timestamp with time zone,
  CONSTRAINT "collections_pkey" PRIMARY KEY (id),
  CONSTRAINT "collections_status_check" CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text])))
);

ALTER TABLE "public"."collections"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."comments" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "collection_id" uuid                     NOT NULL,
  "user_id"       uuid                     NOT NULL,
  "content"       text                     NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "removed_at"    timestamp with time zone,
  CONSTRAINT "comments_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."comments"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."content_filter_terms" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "term"       text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "content_filter_terms_pkey" PRIMARY KEY (id),
  CONSTRAINT "content_filter_terms_term_key" UNIQUE (term)
);

ALTER TABLE "public"."content_filter_terms"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."follow_requests" (
  "id"                uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "requester_user_id" uuid                     NOT NULL,
  "recipient_user_id" uuid                     NOT NULL,
  "status"            text                     NOT NULL DEFAULT 'pending'::text,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"        timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "follow_requests_no_self_request" CHECK ((requester_user_id <> recipient_user_id)),
  CONSTRAINT "follow_requests_pkey" PRIMARY KEY (id),
  CONSTRAINT "follow_requests_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text]))),
  CONSTRAINT "follow_requests_unique_relationship" UNIQUE (requester_user_id, recipient_user_id)
);

ALTER TABLE "public"."follow_requests"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."follows" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "follower_id"  uuid                     NOT NULL,
  "following_id" uuid                     NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "follows_no_self_follow" CHECK ((follower_id <> following_id)),
  CONSTRAINT "follows_pkey" PRIMARY KEY (id),
  CONSTRAINT "follows_unique_relationship" UNIQUE (follower_id, following_id)
);

ALTER TABLE "public"."follows"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."likes" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"       uuid                     NOT NULL,
  "collection_id" uuid                     NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "likes_pkey" PRIMARY KEY (id),
  CONSTRAINT "likes_user_collection_unique" UNIQUE (user_id, collection_id)
);

ALTER TABLE "public"."likes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."moderation_content_removals" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "target_type" text                     NOT NULL,
  "target_id"   uuid                     NOT NULL,
  "removed_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "user_id"     uuid,
  CONSTRAINT "moderation_content_removals_pkey" PRIMARY KEY (id),
  CONSTRAINT "moderation_content_removals_target_type_check" CHECK ((target_type = ANY (ARRAY['post'::text, 'comment'::text])))
);

ALTER TABLE "public"."moderation_content_removals"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."notifications" (
  "id"                uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "recipient_user_id" uuid                     NOT NULL,
  "actor_user_id"     uuid                     NOT NULL,
  "type"              text                     NOT NULL,
  "collection_id"     uuid,
  "comment_id"        uuid,
  "is_read"           boolean                  NOT NULL DEFAULT false,
  "created_at"        timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "notifications_pkey" PRIMARY KEY (id),
  CONSTRAINT "notifications_type_check" CHECK ((type = ANY (ARRAY['like'::text, 'comment'::text, 'follow'::text, 'follow_request_accepted'::text])))
);

ALTER TABLE "public"."notifications"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"                       uuid                     NOT NULL,
  "username"                 text                     NOT NULL,
  "display_name"             text                     NOT NULL,
  "bio"                      text                     NOT NULL DEFAULT ''::text,
  "is_public"                boolean                  NOT NULL DEFAULT true,
  "created_at"               timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"               timestamp with time zone NOT NULL DEFAULT now(),
  "avatar_url"               text,
  "has_completed_onboarding" boolean                  NOT NULL DEFAULT false,
  "is_admin"                 boolean                  NOT NULL DEFAULT false,
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id),
  CONSTRAINT "profiles_username_key" UNIQUE (username)
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."push_tokens" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"         uuid                     NOT NULL,
  "expo_push_token" text                     NOT NULL,
  "platform"        text                     NOT NULL,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "push_tokens_expo_push_token_key" UNIQUE (expo_push_token),
  CONSTRAINT "push_tokens_pkey" PRIMARY KEY (id),
  CONSTRAINT "push_tokens_platform_check" CHECK ((platform = ANY (ARRAY['ios'::text, 'android'::text])))
);

ALTER TABLE "public"."push_tokens"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reports" (
  "id"                  uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "reporter_id"         uuid                     NOT NULL,
  "reported_user_id"    uuid                     NOT NULL,
  "reason"              text                     NOT NULL,
  "details"             text,
  "status"              text                     NOT NULL DEFAULT 'pending'::text,
  "created_at"          timestamp with time zone NOT NULL DEFAULT now(),
  "target_type"         text                     NOT NULL DEFAULT 'user'::text,
  "reported_post_id"    text,
  "reported_comment_id" uuid,
  "reviewed_at"         timestamp with time zone,
  "resolution"          text,
  "moderator_notes"     text,
  CONSTRAINT "reports_cannot_report_self" CHECK ((reporter_id <> reported_user_id)),
  CONSTRAINT "reports_pkey" PRIMARY KEY (id),
  CONSTRAINT "reports_reason_check"
    CHECK ((reason = ANY (ARRAY['spam'::text, 'harassment'::text, 'hate_or_abuse'::text, 'inappropriate_content'::text, 'impersonation'::text, 'other'::text]))),
  CONSTRAINT "reports_resolution_check"
    CHECK (((resolution IS NULL) OR (resolution = ANY (ARRAY['no_action'::text, 'content_removed'::text, 'user_warned'::text, 'user_suspended'::text, 'user_banned'::text])))),
  CONSTRAINT "reports_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'reviewed'::text, 'resolved'::text, 'dismissed'::text]))),
  CONSTRAINT "reports_target_fields_check"
    CHECK ((((target_type = 'user'::text) AND (reported_post_id IS NULL) AND (reported_comment_id IS NULL)) OR ((target_type = 'post'::text) AND (reported_post_id IS
    NOT NULL) AND (reported_comment_id IS NULL)) OR ((target_type = 'comment'::text) AND (reported_post_id IS NULL) AND (reported_comment_id IS NOT NULL)))),
  CONSTRAINT "reports_target_type_check" CHECK ((target_type = ANY (ARRAY['user'::text, 'post'::text, 'comment'::text])))
);

ALTER TABLE "public"."reports"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.accept_follow_request (
  request_id uuid
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  current_user_id uuid := auth.uid();
  request_record public.follow_requests%rowtype;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  select *
  into request_record
  from public.follow_requests
  where id = request_id
    and status = 'pending';

  if not found then
    raise exception 'Follow request not found.';
  end if;

  if request_record.recipient_user_id <> current_user_id then
    raise exception 'Not authorized.';
  end if;

  insert into public.follows (
    follower_id,
    following_id
  )
  values (
    request_record.requester_user_id,
    request_record.recipient_user_id
  )
  on conflict do nothing;

  update public.follow_requests
  set
    status = 'accepted',
    updated_at = now()
  where id = request_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.block_user (
  target_user_id uuid
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if target_user_id is null then
    raise exception 'Target user is required';
  end if;

  if current_user_id = target_user_id then
    raise exception 'A user cannot block themselves';
  end if;

  insert into public.blocks (
    blocker_id,
    blocked_user_id
  )
  values (
    current_user_id,
    target_user_id
  )
  on conflict do nothing;

  delete from public.follows
  where
    (
      follower_id = current_user_id
      and following_id = target_user_id
    )
    or
    (
      follower_id = target_user_id
      and following_id = current_user_id
    );
end;
$function$;

CREATE OR REPLACE FUNCTION public.can_create_direct_follow (
  target_user_id uuid
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select
    auth.uid() is not null
    and target_user_id is not null
    and target_user_id <> auth.uid()

    -- Direct follows are only allowed for public accounts.
    and exists (
      select 1
      from public.profiles p
      where p.id = target_user_id
        and p.is_public = true
    )

    -- Neither user may have blocked the other.
    and not exists (
      select 1
      from public.blocks b
      where
        (
          b.blocker_id = auth.uid()
          and b.blocked_user_id = target_user_id
        )
        or
        (
          b.blocker_id = target_user_id
          and b.blocked_user_id = auth.uid()
        )
    );
$function$;

CREATE OR REPLACE FUNCTION public.can_create_follow_request (
  target_user_id uuid
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select
    auth.uid() is not null
    and target_user_id is not null
    and target_user_id <> auth.uid()

    -- Follow requests are only for private accounts.
    and exists (
      select 1
      from public.profiles p
      where p.id = target_user_id
        and p.is_public = false
    )

    -- Do not allow a request if the relationship already exists.
    and not exists (
      select 1
      from public.follows f
      where f.follower_id = auth.uid()
        and f.following_id = target_user_id
    )

    -- Neither side may have blocked the other.
    and not exists (
      select 1
      from public.blocks b
      where
        (
          b.blocker_id = auth.uid()
          and b.blocked_user_id = target_user_id
        )
        or
        (
          b.blocker_id = target_user_id
          and b.blocked_user_id = auth.uid()
        )
    );
$function$;

CREATE OR REPLACE FUNCTION public.can_view_profile (
  profile_user_id uuid
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select
    case
      when auth.uid() is null then false
      when profile_user_id = auth.uid() then true
      else not exists (
        select 1
        from public.blocks b
        where b.blocker_id = profile_user_id
          and b.blocked_user_id = auth.uid()
      )
    end;
$function$;

CREATE OR REPLACE FUNCTION public.can_view_published_collection (
  collection_owner_id uuid
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select
    collection_owner_id is not null
    and not exists (
      select 1
      from public.blocks b
      where
        (
          b.blocker_id = auth.uid()
          and b.blocked_user_id = collection_owner_id
        )
        or
        (
          b.blocker_id = collection_owner_id
          and b.blocked_user_id = auth.uid()
        )
    )
    and (
      exists (
        select 1
        from public.profiles p
        where p.id = collection_owner_id
          and p.is_public = true
      )
      or (
        auth.uid() is not null
        and exists (
          select 1
          from public.follows f
          where f.follower_id = auth.uid()
            and f.following_id = collection_owner_id
        )
      )
    );
$function$;

CREATE OR REPLACE FUNCTION public.contains_blocked_content (
  input_text text
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select exists (
    select 1
    from public.content_filter_terms t
    where
      input_text is not null
      and btrim(input_text) <> ''
      and (
        ' ' ||
        lower(
          regexp_replace(
            input_text,
            '[^[:alnum:]_]+',
            ' ',
            'g'
          )
        ) ||
        ' '
      ) like (
        '% ' ||
        lower(
          regexp_replace(
            t.term,
            '[^[:alnum:]_]+',
            ' ',
            'g'
          )
        ) ||
        ' %'
      )
  );
$function$;

CREATE OR REPLACE FUNCTION public.create_comment_notification()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  collection_owner_id uuid;
begin
  select user_id
  into collection_owner_id
  from public.collections
  where id = new.collection_id;

  if collection_owner_id is null then
    return new;
  end if;

  if collection_owner_id = new.user_id then
    return new;
  end if;

  insert into public.notifications (
    recipient_user_id,
    actor_user_id,
    type,
    collection_id,
    comment_id
  )
  values (
    collection_owner_id,
    new.user_id,
    'comment',
    new.collection_id,
    new.id
  );

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_follow_notification()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
begin
  if new.follower_id = new.following_id then
    return new;
  end if;

  insert into public.notifications (
    recipient_user_id,
    actor_user_id,
    type
  )
  values (
    new.following_id,
    new.follower_id,
    'follow'
  )
  on conflict do nothing;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_follow_request_accepted_notification()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
begin
  insert into public.notifications (
    recipient_user_id,
    actor_user_id,
    type
  )
  values (
    new.requester_user_id,
    new.recipient_user_id,
    'follow_request_accepted'
  );

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_like_notification()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  collection_owner_id uuid;
begin
  select user_id
  into collection_owner_id
  from public.collections
  where id = new.collection_id;

  if collection_owner_id is null then
    return new;
  end if;

  if collection_owner_id = new.user_id then
    return new;
  end if;

  insert into public.notifications (
    recipient_user_id,
    actor_user_id,
    type,
    collection_id
  )
  values (
    collection_owner_id,
    new.user_id,
    'like',
    new.collection_id
  )
  on conflict do nothing;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_visible_comment_counts (
  collection_ids uuid[]
)
  RETURNS TABLE (
    collection_id uuid,
    comment_count bigint
  )
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select
    c.collection_id,
    count(*) as comment_count
  from public.comments c
  where
    c.collection_id = any(collection_ids)
    and c.removed_at is null
    and exists (
      select 1
      from public.collections col
      where col.id = c.collection_id
        and (
          col.user_id = auth.uid()
          or (
            col.status = 'published'
            and col.published_at is not null
            and col.removed_at is null
            and public.can_view_published_collection(
              col.user_id
            )
          )
        )
    )
    and not exists (
      select 1
      from public.blocks b
      where
        (
          b.blocker_id = auth.uid()
          and b.blocked_user_id = c.user_id
        )
        or
        (
          b.blocker_id = c.user_id
          and b.blocked_user_id = auth.uid()
        )
    )
  group by c.collection_id;
$function$;

CREATE OR REPLACE FUNCTION public.register_push_token (
  p_expo_push_token text,
  p_platform        text
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  current_user_id uuid;
begin
  current_user_id := auth.uid();

  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_platform not in ('ios', 'android') then
    raise exception 'Invalid push token platform';
  end if;

  delete from public.push_tokens
  where expo_push_token = p_expo_push_token
    and user_id <> current_user_id;

  insert into public.push_tokens (
    user_id,
    expo_push_token,
    platform,
    updated_at
  )
  values (
    current_user_id,
    p_expo_push_token,
    p_platform,
    now()
  )
  on conflict (expo_push_token)
  do update set
    user_id = excluded.user_id,
    platform = excluded.platform,
    updated_at = now();
end;
$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.search_visible_profiles (
  search_query text,
  result_limit integer DEFAULT 20
)
  RETURNS TABLE (
    id                       uuid,
    username                 text,
    display_name             text,
    bio                      text,
    avatar_url               text,
    is_public                boolean,
    has_completed_onboarding boolean,
    is_admin                 boolean
  )
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select
    p.id,
    p.username,
    p.display_name,
    p.bio,
    p.avatar_url,
    p.is_public,
    p.has_completed_onboarding,
    p.is_admin
  from public.profiles p
  where
    auth.uid() is not null
    and p.id <> auth.uid()
    and (
      p.username ilike '%' || search_query || '%'
      or p.display_name ilike '%' || search_query || '%'
    )

    -- Hide relationships blocked in either direction.
    and not exists (
      select 1
      from public.blocks b
      where
        (
          b.blocker_id = auth.uid()
          and b.blocked_user_id = p.id
        )
        or
        (
          b.blocker_id = p.id
          and b.blocked_user_id = auth.uid()
        )
    )

  order by p.display_name asc
  limit least(
    greatest(coalesce(result_limit, 20), 1),
    20
  );
$function$;

CREATE OR REPLACE FUNCTION public.set_push_tokens_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path TO ''
  AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.validate_comment_content()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
begin
  if public.contains_blocked_content(new.content) then
    raise exception
      using
        errcode = 'P0001',
        message = 'COMMENT_BLOCKED_CONTENT';
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.validate_profile_content()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
begin
  if public.contains_blocked_content(new.display_name) then
    raise exception
      using
        errcode = 'P0001',
        message = 'PROFILE_DISPLAY_NAME_BLOCKED_CONTENT';
  end if;

  if public.contains_blocked_content(new.username) then
    raise exception
      using
        errcode = 'P0001',
        message = 'PROFILE_USERNAME_BLOCKED_CONTENT';
  end if;

  if public.contains_blocked_content(new.bio) then
    raise exception
      using
        errcode = 'P0001',
        message = 'PROFILE_BIO_BLOCKED_CONTENT';
  end if;

  return new;
end;
$function$;

ALTER TABLE "public"."apple_auth_tokens"
  ADD CONSTRAINT "apple_auth_tokens_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."blocks"
  ADD CONSTRAINT "blocks_blocked_user_id_fkey" FOREIGN KEY (blocked_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."blocks"
  ADD CONSTRAINT "blocks_blocker_id_fkey" FOREIGN KEY (blocker_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."comments"
  ADD CONSTRAINT "comments_collection_id_fkey" FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;

ALTER TABLE "public"."likes"
  ADD CONSTRAINT "likes_collection_id_fkey" FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;

ALTER TABLE "public"."notifications"
  ADD CONSTRAINT "notifications_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."notifications"
  ADD CONSTRAINT "notifications_collection_id_fkey" FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;

ALTER TABLE "public"."notifications"
  ADD CONSTRAINT "notifications_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON DELETE CASCADE;

ALTER TABLE "public"."notifications"
  ADD CONSTRAINT "notifications_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."collections"
  ADD CONSTRAINT "collections_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."comments"
  ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."follow_requests"
  ADD CONSTRAINT "follow_requests_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."follow_requests"
  ADD CONSTRAINT "follow_requests_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."follows"
  ADD CONSTRAINT "follows_follower_id_fkey" FOREIGN KEY (follower_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."follows"
  ADD CONSTRAINT "follows_following_id_fkey" FOREIGN KEY (following_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."likes"
  ADD CONSTRAINT "likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."push_tokens"
  ADD CONSTRAINT "push_tokens_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reports"
  ADD CONSTRAINT "reports_reported_user_id_fkey" FOREIGN KEY (reported_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reports"
  ADD CONSTRAINT "reports_reporter_id_fkey" FOREIGN KEY (reporter_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX blocks_blocked_user_id_idx ON public.blocks USING btree (blocked_user_id);

CREATE INDEX collections_published_feed_idx ON public.collections USING btree (published_at DESC, user_id, id)
  WHERE ((status = 'published'::text) AND (removed_at IS NULL) AND (published_at IS NOT NULL));

CREATE UNIQUE INDEX collections_unique_identity ON public.collections
  USING btree (user_id, lower(TRIM(BOTH FROM category)), COALESCE(lower(TRIM(BOTH FROM TYPE)), 'general'::text), COALESCE(lower(TRIM(BOTH FROM topic)), 'general'::text))
  WHERE (removed_at IS NULL);

CREATE INDEX comments_collection_id_idx ON public.comments USING btree (collection_id);

CREATE INDEX comments_user_id_idx ON public.comments USING btree (user_id);

CREATE INDEX follow_requests_recipient_user_id_idx ON public.follow_requests USING btree (recipient_user_id);

CREATE INDEX follow_requests_requester_user_id_idx ON public.follow_requests USING btree (requester_user_id);

CREATE INDEX follow_requests_status_idx ON public.follow_requests USING btree (status);

CREATE INDEX follows_follower_id_idx ON public.follows USING btree (follower_id);

CREATE INDEX follows_following_id_idx ON public.follows USING btree (following_id);

CREATE INDEX likes_collection_id_idx ON public.likes USING btree (collection_id);

CREATE INDEX likes_user_id_idx ON public.likes USING btree (user_id);

CREATE INDEX moderation_content_removals_user_id_idx ON public.moderation_content_removals USING btree (user_id);

CREATE INDEX notifications_recipient_created_at_idx ON public.notifications USING btree (recipient_user_id, created_at DESC);

CREATE INDEX push_tokens_user_id_idx ON public.push_tokens USING btree (user_id);

CREATE INDEX reports_reported_post_id_idx ON public.reports USING btree (reported_post_id)
  WHERE (reported_post_id IS NOT NULL);

CREATE INDEX reports_reported_user_id_idx ON public.reports USING btree (reported_user_id);

CREATE INDEX reports_reporter_id_idx ON public.reports USING btree (reporter_id);

CREATE INDEX reports_status_idx ON public.reports USING btree (status);

CREATE TRIGGER create_comment_notification_trigger
  AFTER INSERT ON public.comments
  FOR EACH ROW
  EXECUTE FUNCTION public.create_comment_notification();

CREATE TRIGGER validate_comment_content_trigger
  BEFORE INSERT OR UPDATE OF content ON public.comments
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_comment_content();

CREATE TRIGGER create_follow_request_accepted_notification_trigger
  AFTER UPDATE OF status ON public.follow_requests
  FOR EACH ROW
  WHEN (((old.status = 'pending'::text) AND (new.status = 'accepted'::text)))
  EXECUTE FUNCTION public.create_follow_request_accepted_notification();

CREATE TRIGGER create_follow_notification_trigger
  AFTER INSERT ON public.follows
  FOR EACH ROW
  EXECUTE FUNCTION public.create_follow_notification();

CREATE TRIGGER create_like_notification_after_insert
  AFTER INSERT ON public.likes
  FOR EACH ROW
  EXECUTE FUNCTION public.create_like_notification();

CREATE TRIGGER send_push_notification
  AFTER INSERT ON public.notifications
  FOR EACH ROW
  EXECUTE FUNCTION
    supabase_functions.http_request('https://nxtowcheatxouypzqkzc.supabase.co/functions/v1/send-push-notification', 'POST',
    '{"Content-type":"application/json","apikey":"SUPABASE_API_KEY_REQUIRED_AT_DEPLOYMENT"}', '{}', '5000');

CREATE TRIGGER validate_profile_content_trigger
  BEFORE INSERT OR UPDATE OF display_name, username, bio ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_profile_content();

CREATE TRIGGER set_push_tokens_updated_at
  BEFORE UPDATE ON public.push_tokens
  FOR EACH ROW
  EXECUTE FUNCTION public.set_push_tokens_updated_at();

CREATE POLICY "Users can create their own blocks" ON "public"."blocks"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((( SELECT auth.uid() AS uid) = blocker_id) AND (blocker_id <> blocked_user_id)));

CREATE POLICY "Users can delete their own blocks" ON "public"."blocks"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = blocker_id));

CREATE POLICY "Users can view their own blocks" ON "public"."blocks"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = blocker_id));

CREATE POLICY "Anonymous users can view published collections" ON "public"."collections"
  FOR SELECT
  TO "anon"
  USING (((status = 'published'::text) AND (published_at IS NOT NULL) AND (removed_at IS NULL) AND public.can_view_published_collection(user_id)));

CREATE POLICY "Users can create their own collections" ON "public"."collections"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete their own collections" ON "public"."collections"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update their own collections" ON "public"."collections"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view published collections" ON "public"."collections"
  FOR SELECT
  TO "authenticated"
  USING (((status = 'published'::text) AND (published_at IS NOT NULL) AND (removed_at IS NULL) AND public.can_view_published_collection(user_id)));

CREATE POLICY "Users can view their own collections" ON "public"."collections"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can comment on visible published collections" ON "public"."comments"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM public.collections col
  WHERE ((col.id = comments.collection_id) AND (col.status = 'published'::text) AND (col.published_at IS NOT NULL) AND (col.removed_at IS NULL))))));

CREATE POLICY "Users can delete their own comments" ON "public"."comments"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can read comments on visible collections" ON "public"."comments"
  FOR SELECT
  TO "authenticated"
  USING (((removed_at IS NULL) AND (EXISTS ( SELECT 1
   FROM public.collections col
  WHERE (col.id = comments.collection_id)))));

CREATE POLICY "Users can update their own comments" ON "public"."comments"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM public.collections col
  WHERE ((col.id = comments.collection_id) AND (col.status = 'published'::text) AND (col.published_at IS NOT NULL) AND (col.removed_at IS NULL))))));

CREATE POLICY "Recipients can decline follow requests" ON "public"."follow_requests"
  FOR UPDATE
  TO "authenticated"
  USING (((auth.uid() = recipient_user_id) AND (status = 'pending'::text)))
  WITH CHECK (((auth.uid() = recipient_user_id) AND (status = 'declined'::text)));

CREATE POLICY "Requesters can resend declined follow requests" ON "public"."follow_requests"
  FOR UPDATE
  TO "authenticated"
  USING (((auth.uid() = requester_user_id) AND (status = 'declined'::text)))
  WITH CHECK (((auth.uid() = requester_user_id) AND (status = 'pending'::text) AND public.can_create_follow_request(recipient_user_id)));

CREATE POLICY "Users can delete their follow requests" ON "public"."follow_requests"
  FOR DELETE
  TO "authenticated"
  USING (((auth.uid() = requester_user_id) OR (auth.uid() = recipient_user_id)));

CREATE POLICY "Users can request private accounts" ON "public"."follow_requests"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((auth.uid() = requester_user_id) AND public.can_create_follow_request(recipient_user_id)));

CREATE POLICY "Users can view their follow requests" ON "public"."follow_requests"
  FOR SELECT
  TO "authenticated"
  USING (((auth.uid() = requester_user_id) OR (auth.uid() = recipient_user_id)));

CREATE POLICY "Public follows are viewable by everyone" ON "public"."follows"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can delete follow relationships" ON "public"."follows"
  FOR DELETE
  TO "authenticated"
  USING (((auth.uid() = follower_id) OR (auth.uid() = following_id)));

CREATE POLICY "Users can delete their own follows" ON "public"."follows"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = follower_id));

CREATE POLICY "Users can follow public accounts" ON "public"."follows"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((auth.uid() = follower_id) AND public.can_create_direct_follow(following_id)));

CREATE POLICY "Users can delete their own likes" ON "public"."likes"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can like visible published collections" ON "public"."likes"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM public.collections col
  WHERE ((col.id = likes.collection_id) AND (col.status = 'published'::text) AND (col.published_at IS NOT NULL) AND (col.removed_at IS NULL))))));

CREATE POLICY "Users can read likes on visible published collections" ON "public"."likes"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.collections col
  WHERE ((col.id = likes.collection_id) AND (col.status = 'published'::text) AND (col.published_at IS NOT NULL) AND (col.removed_at IS NULL)))));

CREATE POLICY "Users can read own moderation removal events" ON "public"."moderation_content_removals"
  FOR SELECT
  TO "authenticated"
  USING ((user_id = auth.uid()));

CREATE POLICY "Users can read their own notifications" ON "public"."notifications"
  FOR SELECT
  TO "authenticated"
  USING ((recipient_user_id = auth.uid()));

CREATE POLICY "Users can update their own notifications" ON "public"."notifications"
  FOR UPDATE
  TO "authenticated"
  USING ((recipient_user_id = auth.uid()))
  WITH CHECK ((recipient_user_id = auth.uid()));

CREATE POLICY "Authenticated users can view permitted profiles" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING (public.can_view_profile(id));

CREATE POLICY "Users can insert their own profile" ON "public"."profiles"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "Users can update their own profile" ON "public"."profiles"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = id));

CREATE POLICY "Users can delete own push tokens" ON "public"."push_tokens"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert own push tokens" ON "public"."push_tokens"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can update own push tokens" ON "public"."push_tokens"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view own push tokens" ON "public"."push_tokens"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can create their own reports" ON "public"."reports"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((( SELECT auth.uid() AS uid) = reporter_id) AND (reporter_id <> reported_user_id)));

CREATE POLICY "Users can view their own reports" ON "public"."reports"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = reporter_id));

CREATE POLICY "Users can delete their own avatar" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

CREATE POLICY "Users can read their own avatar objects" ON "storage"."objects"
  FOR SELECT
  TO "authenticated"
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

CREATE POLICY "Users can update their own avatar" ON "storage"."objects"
  FOR UPDATE
  TO "authenticated"
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)))
  WITH CHECK (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

CREATE POLICY "Users can upload their own avatar" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."collections";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."comments";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."follows";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."likes";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."moderation_content_removals";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."notifications";

COMMENT ON EXTENSION "pg_net" IS 'Async HTTP';

REVOKE ALL ON FUNCTION "public"."accept_follow_request"(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."accept_follow_request"(uuid) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."block_user"(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."block_user"(uuid) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."can_create_direct_follow"(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."can_create_direct_follow"(uuid) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."can_create_follow_request"(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."can_create_follow_request"(uuid) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."can_view_profile"(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."can_view_profile"(uuid) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."can_view_published_collection"(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."can_view_published_collection"(uuid) TO "anon", "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."contains_blocked_content"(text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."contains_blocked_content"(text) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."create_comment_notification"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_comment_notification"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."create_follow_notification"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_follow_notification"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."create_follow_request_accepted_notification"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_follow_request_accepted_notification"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."create_like_notification"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_like_notification"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."get_visible_comment_counts"(uuid[]) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_visible_comment_counts"(uuid[]) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."register_push_token"(text, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."register_push_token"(text, text) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."rls_auto_enable"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."search_visible_profiles"(text, integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."search_visible_profiles"(text, integer) TO "authenticated", "postgres";

GRANT EXECUTE ON FUNCTION "public"."set_push_tokens_updated_at"() TO PUBLIC, "postgres";

REVOKE ALL ON FUNCTION "public"."validate_comment_content"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."validate_comment_content"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."validate_profile_content"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."validate_profile_content"() TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."apple_auth_tokens" TO "postgres", "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."blocks" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."blocks" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."blocks" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."blocks" TO "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."collections" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."collections" TO "authenticated", "postgres";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."collections" TO "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."comments" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comments" TO "authenticated", "postgres";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comments" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."content_filter_terms" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."content_filter_terms" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."follow_requests" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."follow_requests" TO "authenticated", "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."follow_requests" TO "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."follows" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."follows" TO "authenticated", "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."follows" TO "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."likes" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."likes" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."likes" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."likes" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."moderation_content_removals" TO "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."moderation_content_removals" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."moderation_content_removals" TO "postgres";

GRANT INSERT, MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."moderation_content_removals" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notifications" TO "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notifications" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notifications" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notifications" TO "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."profiles" TO "anon";

GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "postgres";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."profiles" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."push_tokens" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."push_tokens" TO "authenticated", "postgres";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."push_tokens" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reports" TO "anon";

GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."reports" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reports" TO "postgres";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reports" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "service_role";
