create table public.collection_options (
  id text primary key,
  slug text not null,
  category_id text not null,
  kind text not null,
  name text not null,
  group_name text,
  browse_label text,
  keywords text[] not null default '{}',
  search_hints text[] not null default '{}',
  featured boolean not null default false,
  trending_enabled boolean not null default false,
  active boolean not null default true,
  display_order integer not null default 0,
  entity_kind text,
  provider_key text,
  provider_mode text,
  provider_config jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint collection_options_id_check
    check (btrim(id) <> ''),

  constraint collection_options_category_check
    check (
      category_id in (
        'albums',
        'artists',
        'books',
        'games',
        'movies',
        'podcasts',
        'songs',
        'tv'
      )
    ),

  constraint collection_options_kind_check
    check (kind in ('type', 'theme')),

  constraint collection_options_name_check
    check (btrim(name) <> ''),

  constraint collection_options_slug_check
    check (btrim(slug) <> ''),

  constraint collection_options_provider_config_check
    check (jsonb_typeof(provider_config) = 'object'),

  constraint collection_options_category_kind_slug_key
    unique (category_id, kind, slug)
);

alter table public.collection_options
  enable row level security;

create index collection_options_active_browse_idx
  on public.collection_options (
    category_id,
    kind,
    active,
    display_order,
    name
  );

create table public.collection_option_suggestions (
  id bigint generated by default as identity primary key,
  option_id text not null
    references public.collection_options(id)
    on delete cascade,
  item_id text not null,
  item jsonb not null,
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint collection_option_suggestions_item_id_check
    check (btrim(item_id) <> ''),

  constraint collection_option_suggestions_item_check
    check (
      jsonb_typeof(item) = 'object'
      and coalesce(item ->> 'id', '') = item_id
      and btrim(coalesce(item ->> 'title', '')) <> ''
    ),

  constraint collection_option_suggestions_option_item_key
    unique (option_id, item_id)
);

alter table public.collection_option_suggestions
  enable row level security;

create index collection_option_suggestions_browse_idx
  on public.collection_option_suggestions (
    option_id,
    active,
    display_order,
    id
  );

alter table public.collections
  add column if not exists collection_option_id text;

alter table public.collections
  add constraint collections_collection_option_id_fkey
  foreign key (collection_option_id)
  references public.collection_options(id)
  on delete restrict;

create index collections_collection_option_id_idx
  on public.collections (collection_option_id)
  where collection_option_id is not null;

create unique index collections_unique_option_identity
  on public.collections (
    user_id,
    collection_option_id
  )
  where
    removed_at is null
    and collection_option_id is not null;

create policy "Active collection options are readable"
  on public.collection_options
  for select
  to public
  using (active);

create policy "Active collection option suggestions are readable"
  on public.collection_option_suggestions
  for select
  to public
  using (
    active
    and exists (
      select 1
      from public.collection_options option
      where
        option.id = option_id
        and option.active
    )
  );

grant select
  on table public.collection_options
  to anon, authenticated;

grant select
  on table public.collection_option_suggestions
  to anon, authenticated;

grant all
  on table public.collection_options
  to postgres, service_role;

grant all
  on table public.collection_option_suggestions
  to postgres, service_role;

grant all
  on sequence public.collection_option_suggestions_id_seq
  to postgres, service_role;

create or replace function public.set_collection_option_updated_at()
returns trigger
language plpgsql
set search_path to ''
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create trigger set_collection_options_updated_at
  before update on public.collection_options
  for each row
  execute function public.set_collection_option_updated_at();

create trigger set_collection_option_suggestions_updated_at
  before update on public.collection_option_suggestions
  for each row
  execute function public.set_collection_option_updated_at();


insert into public.collection_options (
  id,
  slug,
  category_id,
  kind,
  name,
  group_name,
  browse_label,
  keywords,
  search_hints,
  featured,
  trending_enabled,
  active,
  display_order,
  entity_kind,
  provider_key,
  provider_mode,
  provider_config
)
values
  (
    'movies-type-actors',
    'actors',
    'movies',
    'type',
    'Actors',
    'people',
    null,
    '{}',
    '{}',
    false,
    false,
    true,
    10,
    'person',
    'tmdb',
    'movie_person',
    '{"personType":"actors"}'::jsonb
  ),
  (
    'movies-type-directors',
    'directors',
    'movies',
    'type',
    'Directors',
    'people',
    null,
    '{}',
    '{}',
    false,
    false,
    true,
    20,
    'person',
    'tmdb',
    'movie_person',
    '{"personType":"directors"}'::jsonb
  ),
  (
    'movies-theme-comfort-movies',
    'comfort-movies',
    'movies',
    'theme',
    'Comfort Movies',
    'mood',
    'Familiar, reassuring films that can be watched over and over again',
    array[
      'comfort',
      'cozy',
      'feel good',
      'feel-good',
      'happy',
      'nostalgia',
      'rewatch'
    ],
    array[
      'Feel-good favourites',
      'Movies you watch again and again',
      'Nostalgic movies'
    ],
    true,
    true,
    true,
    10,
    'movie',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'movies-theme-never-get-tired-of',
    'never-get-tired-of',
    'movies',
    'theme',
    'Movies I Never Get Tired Of',
    'personal',
    'The ones that never lose their appeal',
    array[
      'rewatch',
      'repeat',
      'favourites',
      'favorites',
      'never gets old'
    ],
    array[
      'Movies I can watch forever',
      'All-time favourites',
      'Instant rewatches'
    ],
    true,
    true,
    true,
    20,
    'movie',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'movies-theme-tom-cruise-movies',
    'tom-cruise-movies',
    'movies',
    'theme',
    'Tom Cruise Movies',
    'people',
    'Favourite movies starring Tom Cruise',
    array[
      'tom cruise',
      'actor'
    ],
    array[
      'Mission Impossible',
      'Top Gun',
      'Best Tom Cruise performances'
    ],
    false,
    true,
    true,
    30,
    'movie',
    'tmdb',
    'discover',
    '{"withPeople":500}'::jsonb
  ),
  (
    'movies-theme-netflix-originals',
    'netflix-originals',
    'movies',
    'theme',
    'Netflix Originals',
    'platform',
    'Exclusive to the streaming service',
    array[
      'netflix',
      'netflix original',
      'netflix originals',
      'streaming'
    ],
    array[
      'Best Netflix Originals',
      'Netflix exclusives',
      'Hidden Netflix gems'
    ],
    false,
    true,
    true,
    40,
    'movie',
    'tmdb',
    'discover',
    '{"withCompanies":178464}'::jsonb
  ),
  (
    'movies-theme-1980s-movies',
    '1980s-movies',
    'movies',
    'theme',
    '1980s Movies',
    'era',
    'The films that defined the era and its unique style',
    array[
      '1980s',
      '1980',
      '80s',
      'eighties'
    ],
    array[
      'Best 80s movies',
      '80s classics',
      'Movies from the eighties'
    ],
    true,
    true,
    true,
    50,
    'movie',
    'tmdb',
    'discover',
    '{
      "primaryReleaseDateGte":"1980-01-01",
      "primaryReleaseDateLte":"1989-12-31"
    }'::jsonb
  ),
  (
    'movies-theme-movies-that-made-me-cry',
    'movies-that-made-me-cry',
    'movies',
    'theme',
    'Movies That Made Me Cry',
    'mood',
    'The ones that hit hard emotionally',
    array[
      'cry',
      'sad',
      'emotional',
      'tearjerker'
    ],
    array[
      'Emotional movies',
      'Movies that made me cry',
      'Powerful stories'
    ],
    true,
    true,
    true,
    60,
    'movie',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'movies-theme-see-again-first-time',
    'see-again-first-time',
    'movies',
    'theme',
    'Movies I Wish I Could See Again for the First Time',
    'personal',
    'Unforgettable first-watch experiences',
    array[
      'first time',
      'experience again',
      'surprise',
      'twist',
      'unforgettable'
    ],
    array[
      'Movies with amazing twists',
      'Unforgettable first watches',
      'Movies that surprised me'
    ],
    false,
    true,
    true,
    70,
    'movie',
    null,
    'curated',
    '{}'::jsonb
  );

-- Associate existing known Type and Theme collections with stable option IDs.
-- Leave anything that cannot be matched confidently unchanged.

update public.collections
set collection_option_id = case
  when
    lower(btrim(category)) = 'movies'
    and lower(btrim(coalesce(type, ''))) = 'actors'
    and btrim(coalesce(topic, '')) = ''
    then 'movies-type-actors'

  when
    lower(btrim(category)) = 'movies'
    and lower(btrim(coalesce(type, ''))) = 'directors'
    and btrim(coalesce(topic, '')) = ''
    then 'movies-type-directors'

  when lower(btrim(category)) = 'movies' then
    case lower(btrim(coalesce(theme_id, '')))
      when 'comfort-movies'
        then 'movies-theme-comfort-movies'
      when 'never-get-tired-of'
        then 'movies-theme-never-get-tired-of'
      when 'tom-cruise-movies'
        then 'movies-theme-tom-cruise-movies'
      when 'netflix-originals'
        then 'movies-theme-netflix-originals'
      when '1980s-movies'
        then 'movies-theme-1980s-movies'
      when 'movies-that-made-me-cry'
        then 'movies-theme-movies-that-made-me-cry'
      when 'see-again-first-time'
        then 'movies-theme-see-again-first-time'
      else collection_option_id
    end

  else collection_option_id
end
where
  collection_option_id is null
  and lower(btrim(category)) = 'movies'
  and (
    (
      lower(btrim(coalesce(type, ''))) in (
        'actors',
        'directors'
      )
      and btrim(coalesce(topic, '')) = ''
    )
    or lower(btrim(coalesce(theme_id, ''))) in (
      'comfort-movies',
      'never-get-tired-of',
      'tom-cruise-movies',
      'netflix-originals',
      '1980s-movies',
      'movies-that-made-me-cry',
      'see-again-first-time'
    )
  );

-- Seed existing curated Theme suggestions.

insert into public.collection_option_suggestions (
  option_id,
  item_id,
  item,
  display_order
)
values
  ('movies-theme-comfort-movies', 'theme-comfort-back-to-the-future', '{"id":"theme-comfort-back-to-the-future","title":"Back to the Future"}'::jsonb, 10),
  ('movies-theme-comfort-movies', 'theme-comfort-the-princess-bride', '{"id":"theme-comfort-the-princess-bride","title":"The Princess Bride"}'::jsonb, 20),
  ('movies-theme-comfort-movies', 'theme-comfort-paddington-2', '{"id":"theme-comfort-paddington-2","title":"Paddington 2"}'::jsonb, 30),
  ('movies-theme-comfort-movies', 'theme-comfort-school-of-rock', '{"id":"theme-comfort-school-of-rock","title":"School of Rock"}'::jsonb, 40),
  ('movies-theme-comfort-movies', 'theme-comfort-when-harry-met-sally', '{"id":"theme-comfort-when-harry-met-sally","title":"When Harry Met Sally..."}'::jsonb, 50),
  ('movies-theme-comfort-movies', 'theme-comfort-spirited-away', '{"id":"theme-comfort-spirited-away","title":"Spirited Away"}'::jsonb, 60),
  ('movies-theme-comfort-movies', 'theme-comfort-chef', '{"id":"theme-comfort-chef","title":"Chef"}'::jsonb, 70),
  ('movies-theme-comfort-movies', 'theme-comfort-legally-blonde', '{"id":"theme-comfort-legally-blonde","title":"Legally Blonde"}'::jsonb, 80),
  ('movies-theme-comfort-movies', 'theme-comfort-groundhog-day', '{"id":"theme-comfort-groundhog-day","title":"Groundhog Day"}'::jsonb, 90),
  ('movies-theme-comfort-movies', 'theme-comfort-the-holiday', '{"id":"theme-comfort-the-holiday","title":"The Holiday"}'::jsonb, 100),
  ('movies-theme-comfort-movies', 'theme-comfort-clueless', '{"id":"theme-comfort-clueless","title":"Clueless"}'::jsonb, 110),
  ('movies-theme-comfort-movies', 'theme-comfort-ferris-buellers-day-off', '{"id":"theme-comfort-ferris-buellers-day-off","title":"Ferris Bueller''s Day Off"}'::jsonb, 120),
  ('movies-theme-comfort-movies', 'theme-comfort-youve-got-mail', '{"id":"theme-comfort-youve-got-mail","title":"You''ve Got Mail"}'::jsonb, 130),
  ('movies-theme-comfort-movies', 'theme-comfort-ratatouille', '{"id":"theme-comfort-ratatouille","title":"Ratatouille"}'::jsonb, 140),
  ('movies-theme-comfort-movies', 'theme-comfort-mamma-mia', '{"id":"theme-comfort-mamma-mia","title":"Mamma Mia!"}'::jsonb, 150),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-back-to-the-future', '{"id":"theme-never-tired-back-to-the-future","title":"Back to the Future"}'::jsonb, 10),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-jurassic-park', '{"id":"theme-never-tired-jurassic-park","title":"Jurassic Park"}'::jsonb, 20),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-the-shawshank-redemption', '{"id":"theme-never-tired-the-shawshank-redemption","title":"The Shawshank Redemption"}'::jsonb, 30),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-goodfellas', '{"id":"theme-never-tired-goodfellas","title":"Goodfellas"}'::jsonb, 40),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-raiders-of-the-lost-ark', '{"id":"theme-never-tired-raiders-of-the-lost-ark","title":"Raiders of the Lost Ark"}'::jsonb, 50),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-jaws', '{"id":"theme-never-tired-jaws","title":"Jaws"}'::jsonb, 60),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-groundhog-day', '{"id":"theme-never-tired-groundhog-day","title":"Groundhog Day"}'::jsonb, 70),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-die-hard', '{"id":"theme-never-tired-die-hard","title":"Die Hard"}'::jsonb, 80),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-ferris-buellers-day-off', '{"id":"theme-never-tired-ferris-buellers-day-off","title":"Ferris Bueller''s Day Off"}'::jsonb, 90),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-the-big-lebowski', '{"id":"theme-never-tired-the-big-lebowski","title":"The Big Lebowski"}'::jsonb, 100),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-mean-girls', '{"id":"theme-never-tired-mean-girls","title":"Mean Girls"}'::jsonb, 110),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-the-matrix', '{"id":"theme-never-tired-the-matrix","title":"The Matrix"}'::jsonb, 120),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-pulp-fiction', '{"id":"theme-never-tired-pulp-fiction","title":"Pulp Fiction"}'::jsonb, 130),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-the-silence-of-the-lambs', '{"id":"theme-never-tired-the-silence-of-the-lambs","title":"The Silence of the Lambs"}'::jsonb, 140),
  ('movies-theme-never-get-tired-of', 'theme-never-tired-the-dark-knight', '{"id":"theme-never-tired-the-dark-knight","title":"The Dark Knight"}'::jsonb, 150),
  ('movies-theme-netflix-originals', 'theme-netflix-roma', '{"id":"theme-netflix-roma","title":"Roma"}'::jsonb, 10),
  ('movies-theme-netflix-originals', 'theme-netflix-the-irishman', '{"id":"theme-netflix-the-irishman","title":"The Irishman"}'::jsonb, 20),
  ('movies-theme-netflix-originals', 'theme-netflix-marriage-story', '{"id":"theme-netflix-marriage-story","title":"Marriage Story"}'::jsonb, 30),
  ('movies-theme-netflix-originals', 'theme-netflix-glass-onion', '{"id":"theme-netflix-glass-onion","title":"Glass Onion: A Knives Out Mystery"}'::jsonb, 40),
  ('movies-theme-netflix-originals', 'theme-netflix-all-quiet-on-the-western-front', '{"id":"theme-netflix-all-quiet-on-the-western-front","title":"All Quiet on the Western Front"}'::jsonb, 50),
  ('movies-theme-netflix-originals', 'theme-netflix-the-mitchells-vs-the-machines', '{"id":"theme-netflix-the-mitchells-vs-the-machines","title":"The Mitchells vs. the Machines"}'::jsonb, 60),
  ('movies-theme-netflix-originals', 'theme-netflix-the-trial-of-the-chicago-7', '{"id":"theme-netflix-the-trial-of-the-chicago-7","title":"The Trial of the Chicago 7"}'::jsonb, 70),
  ('movies-theme-netflix-originals', 'theme-netflix-dont-look-up', '{"id":"theme-netflix-dont-look-up","title":"Don''t Look Up"}'::jsonb, 80),
  ('movies-theme-netflix-originals', 'theme-netflix-extraction', '{"id":"theme-netflix-extraction","title":"Extraction"}'::jsonb, 90),
  ('movies-theme-netflix-originals', 'theme-netflix-the-old-guard', '{"id":"theme-netflix-the-old-guard","title":"The Old Guard"}'::jsonb, 100),
  ('movies-theme-netflix-originals', 'theme-netflix-bird-box', '{"id":"theme-netflix-bird-box","title":"Bird Box"}'::jsonb, 110),
  ('movies-theme-netflix-originals', 'theme-netflix-okja', '{"id":"theme-netflix-okja","title":"Okja"}'::jsonb, 120),
  ('movies-theme-netflix-originals', 'theme-netflix-beasts-of-no-nation', '{"id":"theme-netflix-beasts-of-no-nation","title":"Beasts of No Nation"}'::jsonb, 130),
  ('movies-theme-netflix-originals', 'theme-netflix-the-king', '{"id":"theme-netflix-the-king","title":"The King"}'::jsonb, 140),
  ('movies-theme-netflix-originals', 'theme-netflix-society-of-the-snow', '{"id":"theme-netflix-society-of-the-snow","title":"Society of the Snow"}'::jsonb, 150),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-up', '{"id":"theme-cry-up","title":"Up"}'::jsonb, 10),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-the-green-mile', '{"id":"theme-cry-the-green-mile","title":"The Green Mile"}'::jsonb, 20),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-about-time', '{"id":"theme-cry-about-time","title":"About Time"}'::jsonb, 30),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-good-will-hunting', '{"id":"theme-cry-good-will-hunting","title":"Good Will Hunting"}'::jsonb, 40),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-eternal-sunshine', '{"id":"theme-cry-eternal-sunshine","title":"Eternal Sunshine of the Spotless Mind"}'::jsonb, 50),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-life-is-beautiful', '{"id":"theme-cry-life-is-beautiful","title":"Life Is Beautiful"}'::jsonb, 60),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-the-notebook', '{"id":"theme-cry-the-notebook","title":"The Notebook"}'::jsonb, 70),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-room', '{"id":"theme-cry-room","title":"Room"}'::jsonb, 80),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-hachi', '{"id":"theme-cry-hachi","title":"Hachi: A Dog’s Tale"}'::jsonb, 90),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-bridge-to-terabithia', '{"id":"theme-cry-bridge-to-terabithia","title":"Bridge to Terabithia"}'::jsonb, 100),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-coco', '{"id":"theme-cry-coco","title":"Coco"}'::jsonb, 110),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-terms-of-endearment', '{"id":"theme-cry-terms-of-endearment","title":"Terms of Endearment"}'::jsonb, 120),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-the-fault-in-our-stars', '{"id":"theme-cry-the-fault-in-our-stars","title":"The Fault in Our Stars"}'::jsonb, 130),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-man-of-steel', '{"id":"theme-cry-man-of-steel","title":"Man of Steel"}'::jsonb, 140),
  ('movies-theme-movies-that-made-me-cry', 'theme-cry-a-star-is-born', '{"id":"theme-cry-a-star-is-born","title":"A Star Is Born"}'::jsonb, 150),
  ('movies-theme-see-again-first-time', 'theme-first-time-the-sixth-sense', '{"id":"theme-first-time-the-sixth-sense","title":"The Sixth Sense"}'::jsonb, 10),
  ('movies-theme-see-again-first-time', 'theme-first-time-the-usual-suspects', '{"id":"theme-first-time-the-usual-suspects","title":"The Usual Suspects"}'::jsonb, 20),
  ('movies-theme-see-again-first-time', 'theme-first-time-inception', '{"id":"theme-first-time-inception","title":"Inception"}'::jsonb, 30),
  ('movies-theme-see-again-first-time', 'theme-first-time-the-prestige', '{"id":"theme-first-time-the-prestige","title":"The Prestige"}'::jsonb, 40),
  ('movies-theme-see-again-first-time', 'theme-first-time-fight-club', '{"id":"theme-first-time-fight-club","title":"Fight Club"}'::jsonb, 50),
  ('movies-theme-see-again-first-time', 'theme-first-time-memento', '{"id":"theme-first-time-memento","title":"Memento"}'::jsonb, 60),
  ('movies-theme-see-again-first-time', 'theme-first-time-get-out', '{"id":"theme-first-time-get-out","title":"Get Out"}'::jsonb, 70),
  ('movies-theme-see-again-first-time', 'theme-first-time-the-matrix', '{"id":"theme-first-time-the-matrix","title":"The Matrix"}'::jsonb, 80),
  ('movies-theme-see-again-first-time', 'theme-first-time-parasite', '{"id":"theme-first-time-parasite","title":"Parasite"}'::jsonb, 90),
  ('movies-theme-see-again-first-time', 'theme-first-time-arrival', '{"id":"theme-first-time-arrival","title":"Arrival"}'::jsonb, 100),
  ('movies-theme-see-again-first-time', 'theme-first-time-the-village', '{"id":"theme-first-time-the-village","title":"The Village"}'::jsonb, 110),
  ('movies-theme-see-again-first-time', 'theme-first-time-se7en', '{"id":"theme-first-time-se7en","title":"Se7en"}'::jsonb, 120),
  ('movies-theme-see-again-first-time', 'theme-first-time-predestination', '{"id":"theme-first-time-predestination","title":"Predestination"}'::jsonb, 130),
  ('movies-theme-see-again-first-time', 'theme-first-time-shutter-island', '{"id":"theme-first-time-shutter-island","title":"Shutter Island"}'::jsonb, 140),
  ('movies-theme-see-again-first-time', 'theme-first-time-the-game', '{"id":"theme-first-time-the-game","title":"The Game"}'::jsonb, 150);
