insert into public.collection_options (
  id,
  slug,
  category_id,
  kind,
  name,
  group_name,
  browse_label,
  keywords,
  search_hints,
  featured,
  trending_enabled,
  active,
  display_order,
  entity_kind,
  provider_key,
  provider_mode,
  provider_config
)
values
  (
    'artists-theme-1960s-artists',
    '1960s-artists',
    'artists',
    'theme',
    '1960s Artists',
    'era',
    'The artists who defined the sound and culture of the decade',
    array['1960s', '1960', '60s', 'sixties'],
    array['Defining artists of the 1960s', '60s music icons'],
    false,
    true,
    true,
    10,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-1970s-artists',
    '1970s-artists',
    'artists',
    'theme',
    '1970s Artists',
    'era',
    'The artists who defined the sound and culture of the decade',
    array['1970s', '1970', '70s', 'seventies'],
    array['Defining artists of the 1970s', '70s music icons'],
    false,
    true,
    true,
    20,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-1980s-artists',
    '1980s-artists',
    'artists',
    'theme',
    '1980s Artists',
    'era',
    'The artists who defined the sound and culture of the decade',
    array['1980s', '1980', '80s', 'eighties'],
    array['Defining artists of the 1980s', '80s music icons'],
    true,
    true,
    true,
    30,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-1990s-artists',
    '1990s-artists',
    'artists',
    'theme',
    '1990s Artists',
    'era',
    'The artists who defined the sound and culture of the decade',
    array['1990s', '1990', '90s', 'nineties'],
    array['Defining artists of the 1990s', '90s music icons'],
    true,
    true,
    true,
    40,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-2000s-artists',
    '2000s-artists',
    'artists',
    'theme',
    '2000s Artists',
    'era',
    'The artists who defined the sound and culture of the decade',
    array['2000s', '2000', '00s', 'aughts'],
    array['Defining artists of the 2000s', '2000s music icons'],
    false,
    true,
    true,
    50,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-2010s-artists',
    '2010s-artists',
    'artists',
    'theme',
    '2010s Artists',
    'era',
    'The artists who defined the sound and culture of the decade',
    array['2010s', '2010', '10s'],
    array['Defining artists of the 2010s', '2010s music icons'],
    false,
    true,
    true,
    60,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-2020s-artists',
    '2020s-artists',
    'artists',
    'theme',
    '2020s Artists',
    'era',
    'The artists defining the sound and culture of the decade',
    array['2020s', '2020', '20s', 'current'],
    array['Artists defining the 2020s', 'Current music icons'],
    false,
    true,
    true,
    70,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-road-trip',
    'road-trip',
    'artists',
    'theme',
    'Road Trip Artists',
    'mood',
    'The artists you want on the soundtrack to a long drive',
    array['road trip', 'driving', 'drive', 'travel'],
    array['Artists for a road trip', 'Driving music'],
    true,
    true,
    true,
    80,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-late-night',
    'late-night',
    'artists',
    'theme',
    'Late-Night Artists',
    'mood',
    'The artists that sound best after dark',
    array['late night', 'night', 'after dark', 'evening'],
    array['Late-night listening', 'Artists for after dark'],
    false,
    true,
    true,
    90,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-party',
    'party',
    'artists',
    'theme',
    'Party Artists',
    'mood',
    'The artists guaranteed to get the room moving',
    array['party', 'dance', 'celebration', 'energy'],
    array['Artists for a party', 'Party favourites'],
    false,
    true,
    true,
    100,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-rainy-day',
    'rainy-day',
    'artists',
    'theme',
    'Rainy Day Artists',
    'mood',
    'The artists that fit a quiet, grey day',
    array['rainy day', 'rain', 'quiet', 'moody'],
    array['Artists for a rainy day', 'Moody listening'],
    false,
    true,
    true,
    110,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-listening-right-now',
    'listening-right-now',
    'artists',
    'theme',
    'Listening Right Now',
    'personal',
    'The artists currently dominating your rotation',
    array['current', 'right now', 'rotation', 'recent', 'listening'],
    array['Artists on repeat right now', 'Current favourites'],
    true,
    true,
    true,
    120,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-discovered-late',
    'discovered-late',
    'artists',
    'theme',
    'Discovered Late',
    'personal',
    'Artists you somehow missed the first time around',
    array['discovered', 'late', 'recent discovery', 'missed'],
    array['Artists I found years later', 'Late discoveries'],
    true,
    true,
    true,
    130,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-came-around-on',
    'came-around-on',
    'artists',
    'theme',
    'Came Around On',
    'personal',
    'Artists you didn’t connect with at first, but do now',
    array['changed my mind', 'grew on me', 'came around', 'appreciate now'],
    array['Artists who grew on me', 'Artists I changed my mind about'],
    false,
    true,
    true,
    140,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-wish-id-seen-live',
    'wish-id-seen-live',
    'artists',
    'theme',
    'Wish I’d Seen Live',
    'live',
    'Artists you wish you could have experienced in their prime',
    array['live', 'concert', 'prime', 'peak', 'wish I saw'],
    array['Legendary live acts', 'Artists I wish I had seen'],
    true,
    true,
    true,
    150,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-worth-travelling-for',
    'worth-travelling-for',
    'artists',
    'theme',
    'Worth Travelling For',
    'live',
    'Artists you’d plan a trip around to see live',
    array['live', 'concert', 'travel', 'tour', 'road trip'],
    array['Artists worth travelling for', 'Must-see live acts'],
    true,
    true,
    true,
    160,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-best-debut-albums',
    'best-debut-albums',
    'artists',
    'theme',
    'Best Debut Albums',
    'career',
    'Artists who made an exceptional first impression',
    array['debut', 'debut album', 'first album', 'first record'],
    array['Best debut albums', 'Great first records'],
    true,
    true,
    true,
    170,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-best-reinventions',
    'best-reinventions',
    'artists',
    'theme',
    'Best Reinventions',
    'career',
    'Artists who successfully evolved their sound or identity',
    array['reinvention', 'reinvented', 'evolution', 'changed sound', 'changed style'],
    array['Best artist reinventions', 'Artists who evolved'],
    false,
    true,
    true,
    180,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  ),
  (
    'artists-theme-deserve-a-comeback',
    'deserve-a-comeback',
    'artists',
    'theme',
    'Deserve a Comeback',
    'career',
    'Artists you’d love to see return with something new',
    array['comeback', 'return', 'reunion', 'new music', 'revival'],
    array['Artists who should come back', 'Acts ready for a return'],
    false,
    true,
    true,
    190,
    'artist',
    null,
    'curated',
    '{}'::jsonb
  );
